# 8-puzzle: IA 1 - Professor Li Weigang
### Fred Guth - 190050411 - 21/03/2019

In [1]:
import numpy as np
from sortedcontainers import SortedDict

__moves__ guarda as movimentações (swaps) possíveis para cada posição do tabuleiro.
O tabuleiro é representado por uma simples lista ou um número. 
Por exemplo, a posição inicial é o estado [5,4,0,6,1,8,7,3,2] e também pode ser representado por 540618732.

In [2]:
moves=np.array([[1,3],[0,2,4],[1,5],[1,4,6],[1,3,5,7],[2,4,8],[3,7],[6,4,8],[5,7]])
initial = [5,4,0,6,1,8,7,3,2] # 0 marks where it is empty
final = [1,2,3,8,0,4,7,6,5]
visited = SortedDict()

In [3]:
# "Troca" alguma posição do tabuleiro com o espaço vazio.  Não verifica se o swap é válido.
def Swap(state, pos):
    empty = state.index(0)
    state[empty], state[pos] = state[pos], state[empty]
    return state

In [4]:
# Imprime o tabuleiro
def PrintBoard(state):
    print (np.asarray(state).reshape((3,3)))

In [5]:
# Transforma a representação do tabuleiro por lista em representação por número
def Numerify(state):
    return int("".join(map(str, state[:]))) 

In [6]:
# Imprime todas as posições do tabuleiro do estado inicial ao "state"
def Trace(state):
    stack = []
    stack.append(state)
    parent = visited[Numerify(state)]['parent']
    while (parent is not None):
        stack.insert(0, parent)
        parent = visited[Numerify(parent)]['parent']
    for i, s in enumerate(stack):
        print(f'position #{i}:')
        PrintBoard(s)

## Primeira Abordagem: BFS
O problema do Breadth-First Search é que não há nenhuma priorização entre os estados enfileirados para serem buscados.

In [7]:
# Breadth-First Search
def BFS(source):
    counter = 0
    visited[Numerify(source)]={'moves': 0, 'parent': None}
    queue = []
    queue.insert(0,source)   
    while (len(queue) > 0):
        u = queue.pop()
        m = visited[Numerify(u)]['moves']
        empty = u.index(0) # where is empty
        for v in moves[empty]:
            state = Swap(u[:], v) # u[:] makes a copy of u
            if not(visited.__contains__(Numerify(state))):
                visited[Numerify(state)]={'moves':m+1, 'parent': u}
                if (Numerify(state) == Numerify(final)):
                        print (f'{counter:,} evaluations.')
                        print (visited[Numerify(state)])
                        return
                else:
                    counter = counter + 1
                    queue.insert(0,state)

In [8]:
BFS(initial)

279,355 evaluations.
{'moves': 25, 'parent': [1, 2, 3, 8, 4, 0, 7, 6, 5]}


In [9]:
Trace(final)

position #0:
[[5 4 0]
 [6 1 8]
 [7 3 2]]
position #1:
[[5 0 4]
 [6 1 8]
 [7 3 2]]
position #2:
[[0 5 4]
 [6 1 8]
 [7 3 2]]
position #3:
[[6 5 4]
 [0 1 8]
 [7 3 2]]
position #4:
[[6 5 4]
 [1 0 8]
 [7 3 2]]
position #5:
[[6 0 4]
 [1 5 8]
 [7 3 2]]
position #6:
[[0 6 4]
 [1 5 8]
 [7 3 2]]
position #7:
[[1 6 4]
 [0 5 8]
 [7 3 2]]
position #8:
[[1 0 4]
 [6 5 8]
 [7 3 2]]
position #9:
[[1 4 0]
 [6 5 8]
 [7 3 2]]
position #10:
[[1 4 8]
 [6 5 0]
 [7 3 2]]
position #11:
[[1 4 8]
 [6 5 2]
 [7 3 0]]
position #12:
[[1 4 8]
 [6 5 2]
 [7 0 3]]
position #13:
[[1 4 8]
 [6 0 2]
 [7 5 3]]
position #14:
[[1 4 8]
 [0 6 2]
 [7 5 3]]
position #15:
[[1 0 8]
 [4 6 2]
 [7 5 3]]
position #16:
[[1 8 0]
 [4 6 2]
 [7 5 3]]
position #17:
[[1 8 2]
 [4 6 0]
 [7 5 3]]
position #18:
[[1 8 2]
 [4 6 3]
 [7 5 0]]
position #19:
[[1 8 2]
 [4 6 3]
 [7 0 5]]
position #20:
[[1 8 2]
 [4 0 3]
 [7 6 5]]
position #21:
[[1 8 2]
 [0 4 3]
 [7 6 5]]
position #22:
[[1 0 2]
 [8 4 3]
 [7 6 5]]
position #23:
[[1 2 0]
 [8 4 3]
 [7 6 5]]
po

## Segunda Abordagem: 

In [10]:
import heapq

In [11]:
moves=np.array([[1,3],[0,2,4],[1,5],[1,4,6],[1,3,5,7],[2,4,8],[3,7],[6,4,8],[5,7]])
initial = [5,4,0,6,1,8,7,3,2] # 0 marks where it is empty
final = [1,2,3,8,0,4,7,6,5]
visited = SortedDict()

In [12]:
# Checa o número de posições diferentes entre dois tabuleiros
def GetDistance(n1, n2):
    s1, s2 = str(Numerify(n1)), str(Numerify(n2))
    return sum(ch1 != ch2 for ch1, ch2 in zip(s1, s2))

In [13]:
# Priority Search: usaremos um heap para fila de prioridade e a função *heuristic* para determinar o custo
def PS(heuristic, source):
    counter = 0
    visited[Numerify(source)]={'moves': 0, 'parent': None}
    h = [] 
    heapq.heappush(h, (0, source))
    while (len(h) > 0):
        u = heapq.heappop(h)[1]
        m = visited[Numerify(u)]['moves']
        empty = u.index(0) # where is empty
        for v in moves[empty]:
            state = Swap(u[:], v) # u[:] makes a copy of u
            if not(visited.__contains__(Numerify(state))):
                visited[Numerify(state)]={'moves':m+1, 'parent': u}
                if (Numerify(state) == Numerify(final)):
                        print (f'{counter:,} evaluations.')
                        print (visited[Numerify(state)])
                        return
                else:
                    counter = counter + 1
                    cost = heuristic(state, final)
                    heapq.heappush(h, ((m + cost), state))

In [14]:
PS(GetDistance, initial)

112,834 evaluations.
{'moves': 27, 'parent': [1, 2, 3, 8, 4, 0, 7, 6, 5]}


In [15]:
Trace(final)

position #0:
[[5 4 0]
 [6 1 8]
 [7 3 2]]
position #1:
[[5 0 4]
 [6 1 8]
 [7 3 2]]
position #2:
[[5 1 4]
 [6 0 8]
 [7 3 2]]
position #3:
[[5 1 4]
 [0 6 8]
 [7 3 2]]
position #4:
[[5 1 4]
 [7 6 8]
 [0 3 2]]
position #5:
[[5 1 4]
 [7 6 8]
 [3 0 2]]
position #6:
[[5 1 4]
 [7 0 8]
 [3 6 2]]
position #7:
[[5 1 4]
 [7 8 0]
 [3 6 2]]
position #8:
[[5 1 4]
 [7 8 2]
 [3 6 0]]
position #9:
[[5 1 4]
 [7 8 2]
 [3 0 6]]
position #10:
[[5 1 4]
 [7 8 2]
 [0 3 6]]
position #11:
[[5 1 4]
 [0 8 2]
 [7 3 6]]
position #12:
[[5 0 4]
 [1 8 2]
 [7 3 6]]
position #13:
[[0 5 4]
 [1 8 2]
 [7 3 6]]
position #14:
[[1 5 4]
 [0 8 2]
 [7 3 6]]
position #15:
[[1 5 4]
 [8 0 2]
 [7 3 6]]
position #16:
[[1 0 4]
 [8 5 2]
 [7 3 6]]
position #17:
[[1 4 0]
 [8 5 2]
 [7 3 6]]
position #18:
[[1 4 2]
 [8 5 0]
 [7 3 6]]
position #19:
[[1 4 2]
 [8 0 5]
 [7 3 6]]
position #20:
[[1 4 2]
 [8 3 5]
 [7 0 6]]
position #21:
[[1 4 2]
 [8 3 5]
 [7 6 0]]
position #22:
[[1 4 2]
 [8 3 0]
 [7 6 5]]
position #23:
[[1 4 2]
 [8 0 3]
 [7 6 5]]
po

## Terceira Abordagem: 

In [16]:
moves=np.array([[1,3],[0,2,4],[1,5],[1,4,6],[1,3,5,7],[2,4,8],[3,7],[6,4,8],[5,7]])
initial = [5,4,0,6,1,8,7,3,2] # 0 marks where it is empty
final = [1,2,3,8,0,4,7,6,5]
visited = SortedDict()

In [17]:
def manhattan_distance(current, goal):
    return sum(abs(b%3 - g%3) + abs(b//3 - g//3)
        for b, g in ((current.index(i), goal.index(i)) for i in range(1, 9)))

In [18]:
PS(manhattan_distance, initial)

3,830 evaluations.
{'moves': 25, 'parent': [1, 2, 3, 8, 4, 0, 7, 6, 5]}
